import { ICJ } from '../core/ICJ';
import { ActionType } from '../enums/actions';
import { generateRandomEmail, generateRandomName, generateRandomStringBirthDate, generateRandomSurname } from '../services/ramdom';

export default <ICJ>{
  name: '[BIKE] - 2a mano',
  actions: [
    {
      type: ActionType.CLICK,
      selector: 'cj-already-bought [id="lbl_Segunda mano comprada a particular"] .card-selector',
      optional: true,
      executeIf: async (): Promise<boolean> => !window?.location?.hash || window?.location?.hash === '#Q1',
    },
    { type: ActionType.CLICK, selector: 'cj-make #li_top_YAMAHA' },
    { type: ActionType.CLICK, selector: 'cj-model #li_NMAX' },
    { type: ActionType.CLICK, selector: 'cj-process-cubic-capacity [id="lbl_125 cc"] .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-version #tltVersion' },
    { type: ActionType.SELECT, selector: 'cj-process-how-old-is-bike #monthOld', numericValue: 4 },
    { type: ActionType.SELECT, selector: 'cj-process-how-old-is-bike #yearOld', numericValue: 3 },
    { type: ActionType.CLICK, selector: 'cj-process-how-old-is-bike #next' },
    { type: ActionType.CLICK, selector: 'cj-process-bike-usage [id="lbl_Uso profesional ocasional"] .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-passenger-type #lbl_Nunca .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-parking-type [id="lbl_En la calle"] .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-annual-km [id="lbl_Hasta 3.000 km"] .card-selector' },
    {
      type: ActionType.TYPE,
      selector: 'cj-process-date-of-birth #txtDateofBirth',
      stringValueFunc: async (): Promise<string> => generateRandomStringBirthDate({ minAge: 25 }),
    },
    { type: ActionType.CLICK, selector: 'cj-process-date-of-birth #next' },
    { type: ActionType.CLICK, selector: 'cj-process-birth-place #lbl_España' },
    { type: ActionType.CLICK, selector: 'cj-process-main-driver-data #lbl_Hombre > div' },
    { type: ActionType.CLICK, selector: 'cj-process-main-driver-data [id="lbl_Soltero / a"] .card-selector', optional: true },
    { type: ActionType.CLICK, selector: 'cj-process-profession #lbl_Directivo .card-selector' },
    { type: ActionType.TYPE, selector: 'cj-process-zipcode #postalCode', stringValue: '28002' },
    { type: ActionType.WAIT_UNTIL_VALUE, selector: 'cj-process-zipcode .result-txt', stringValue: 'MADRID' },
    { type: ActionType.WAIT, numericValue: 1000 },
    { type: ActionType.CLICK, selector: 'cj-process-zipcode #next' },
    { type: ActionType.CLICK, selector: 'app-bike-driver-childs #lbl_No .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-licence-type [id="lbl_A (para conducir todo tipo de motos)"] .card-selector' },
    { type: ActionType.SELECT, selector: 'cj-process-licence-date #month', numericValue: 4 },
    { type: ActionType.SELECT, selector: 'cj-process-licence-date #year', numericValue: 3 },
    { type: ActionType.CLICK, selector: 'cj-process-licence-date #next' },
    { type: ActionType.CLICK, selector: 'cj-process-licence-place #lbl_España' },
    { type: ActionType.CLICK, selector: 'app-last-bike [id="lbl_No tiene, esta es su primera moto"] .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-who-policy-holder [id="lbl_El conductor principal"] .card-selector' },
    { type: ActionType.TYPE, selector: 'app-name #name', stringValueFunc: async (): Promise<string> => generateRandomName() },
    { type: ActionType.TYPE, selector: 'app-name #firstSurName', stringValueFunc: async (): Promise<string> => generateRandomSurname() },
    { type: ActionType.TYPE, selector: 'app-name #secondSurName', stringValueFunc: async (): Promise<string> => generateRandomSurname() },
    { type: ActionType.CLICK, selector: 'app-name #next' },
    { type: ActionType.CLICK, selector: 'app-defaulter #lbl_No .card-selector' },
    { type: ActionType.TYPE, selector: 'cj-process-insurance-holder-dni #txtDniNumber', stringValue: '12345678Z' },
    { type: ActionType.CLICK, selector: 'cj-process-insurance-holder-dni #next' },
    { type: ActionType.CLICK, selector: 'cj-process-insurer-name #lbl_No .card-selector' },
    { type: ActionType.CLICK, selector: 'app-has-claim #lbl_No .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-previous-fine #lbl_No .card-selector' },
    { type: ActionType.CLICK, selector: 'cj-process-initial-doi #next' },
    { type: ActionType.CLICK, selector: 'cj-process-kind-of-insurance [id="lbl_No estoy seguro"] .card-selector' },
    { type: ActionType.TYPE, selector: 'cj-process-email-info #email', stringValueFunc: async (): Promise<string> => generateRandomEmail() },
    { type: ActionType.TYPE, selector: 'cj-process-email-info #phone', stringValue: '910790576' },
    { type: ActionType.CLICK, selector: 'cj-process-email-info #chkTMC' },
    { type: ActionType.CLICK, selector: 'cj-process-email-info #chkCaptcha', optional: true },
    { type: ActionType.CLICK, selector: 'cj-process-email-info #next' },
  ],
};
