import { ICJ } from '../core/ICJ';
import { ActionType } from '../enums/actions';

export default <ICJ>{
  name: '[CAR] - 2a mano - carfax - todos tipos',
  actions: [
    { type: ActionType.CLICK, selector: '#SecondHandFromDealer' },
    { type: ActionType.TYPE, selector: 'app-license-plate input', stringValue: '6458CPS' },
    { type: ActionType.CLICK, selector: '#btnLicensePlateClick' },
    { type: ActionType.CLICK, selector: 'app-license-plate .selector-wrapper .card-selector' },
    { type: ActionType.CLICK, selector: '#MainDriver' },
    { type: ActionType.CLICK, selector: '#div-No' },
    { type: ActionType.CLICK, selector: '#PrivateWork' },
    { type: ActionType.CLICK, selector: '#StreetParking' },
    { type: ActionType.CLICK, selector: '#KM11000' },
    { type: ActionType.CLICK, selector: '#span_No' },
    { type: ActionType.CLICK, selector: '#Two' },
    { type: ActionType.TYPE, selector: 'vehicle-driver-dob input', stringValue: '01/01/1980' },
    { type: ActionType.CLICK, selector: 'vehicle-driver-dob #btn_submit' },
    { type: ActionType.CLICK, selector: "div[title='España']" },
    { type: ActionType.SELECT, selector: '#CJDriverDetailsLicenceDate_Month', numericValue: 2 },
    { type: ActionType.SELECT, selector: '#CJDriverDetailsLicenceDate_Year', numericValue: 3 },
    { type: ActionType.CLICK, selector: 'license-obtain-date #btn_submit' },
    { type: ActionType.CLICK, selector: "license-obtained-place div[title='España']" },
    { type: ActionType.CLICK, selector: 'vehicle-drive-gender #radioMale+div' },
    { type: ActionType.CLICK, selector: '#Single' },
    { type: ActionType.CLICK, selector: 'children-at-home #span_No' },
    { type: ActionType.CLICK, selector: 'vehicle-driver-profession #ComputerTechnician' },
    { type: ActionType.TYPE, selector: 'app-address #txtPostalCode', stringValue: '28002' },
    { type: ActionType.SELECT, selector: 'app-address #driverStreetkind', stringValue: 'Calle' },
    { type: ActionType.TYPE, selector: 'app-address #txtVia', stringValue: 'Sánchez Pacheco' },
    { type: ActionType.TYPE, selector: 'app-address #txtNumero', stringValue: '85' },
    { type: ActionType.WAIT_UNTIL_VALUE, selector: 'app-address #driverTown span.ng-value-label', stringValue: 'Madrid, Madrid' },
    { type: ActionType.CLICK, selector: 'app-address #btnSkipAddress' },
    { type: ActionType.CLICK, selector: 'residence-duration #Between2and3' },
    { type: ActionType.CLICK, selector: 'who-policy-holder #MainDriver' },
    { type: ActionType.TYPE, selector: 'app-dni #txtDniNumber', stringValue: '12345678Z' },
    { type: ActionType.CLICK, selector: 'app-dni #btnDniClick' },
    { type: ActionType.TYPE, selector: 'app-policy-holder-name #txtFistName', stringValue: 'Nombre' },
    { type: ActionType.TYPE, selector: 'app-policy-holder-name #txtMiddleName', stringValue: 'PrimerApellido' },
    { type: ActionType.TYPE, selector: 'app-policy-holder-name #txtLastName', stringValue: 'SegundoApellido' },
    { type: ActionType.CLICK, selector: 'app-policy-holder-name #btnPolicyHolderNameClick' },
    { type: ActionType.CLICK, selector: 'app-defaulter #defaulterNo' },
    { type: ActionType.CLICK, selector: 'app-isocassional-driver #No' },
    { type: ActionType.CLICK, selector: 'insurence-question #No' },
    { type: ActionType.CLICK, selector: 'claim-details #spanNo' },
    { type: ActionType.CLICK, selector: 'fine-details #No' },
    { type: ActionType.CLICK, selector: 'expected-policy-buy-date #btn_submit' },
    { type: ActionType.CLICK, selector: 'cover-type #next' },
    { type: ActionType.TYPE, selector: 'email-with-tele #txtEmail', stringValue: 'automated@fromIt.com' },
    { type: ActionType.TYPE, selector: 'email-with-tele #txtphone', stringValue: '614785236' },
    { type: ActionType.CLICK, selector: 'email-with-tele .checkmark' },
    { type: ActionType.CLICK, selector: 'email-with-tele #btnEmailClick' },
  ],
};
