import { ICJ } from '../core/ICJ';
import { ActionType } from '../enums/actions';
import {
  generateRandomEmail,
  generateRandomName,
  generateRandomStringBirthDate,
  generateRandomSurname,
  generateStringDate,
  generateRandomDNI
} from '../services/random';

export default <ICJ>{
  name: '[Hogar] - Propietario con objetos especiales',
  actions: [
    {
      type: ActionType.CLICK,
      selector: 'app-occupation #divOption_Mine',
      optional: true,
      executeIf: async (): Promise<boolean> => window?.location.pathname?.endsWith('/Q1'),
    },
    { type: ActionType.CLICK, selector: 'app-purpose #divOption_Usually' },
    { type: ActionType.SELECT, selector: 'app-resident-people #HouseSection_PersonInHouse_option', numericValue: 5 },
    { type: ActionType.CLICK, selector: 'app-resident-people #next' },
    { type: ActionType.CLICK, selector: 'app-is-house-insured div[title="Sí"]' },
    { type: ActionType.CLICK, selector: 'app-is-house-insured #Mortgage_0', optional: true, timeout: 500 },
    { type: ActionType.TYPE, selector: 'app-postal-code #div_PostalCode > input', stringValue: '19005' },
    { type: ActionType.WAIT_UNTIL_VALUE, selector: 'app-postal-code #lblCity', stringValue: 'GUADALAJARA', timeout: 90000 },
    { type: ActionType.WAIT, numericValue: 1000 },
    { type: ActionType.CLICK, selector: 'app-postal-code #next' },
    { type: ActionType.CLICK, selector: 'app-kind #divOption_FlatMiddleFloor' },
    { type: ActionType.CLICK, selector: 'app-situation #divOption_CityCentre' },
    { type: ActionType.SELECT, selector: 'app-construction-year #HouseSection__option', stringValue: '2000' },
    { type: ActionType.CLICK, selector: 'app-construction-year #next' },
    { type: ActionType.TYPE, selector: 'app-house-and-land-area #txt_', stringValue: '90' },
    { type: ActionType.CLICK, selector: 'app-house-and-land-area #next' },
    { type: ActionType.SELECT, selector: 'app-number-of-rooms #HouseSection_NumberOfRooms_option', numericValue: 2 },
    { type: ActionType.SELECT, selector: 'app-number-of-rooms #HouseSection_NumberOfBathrooms_option', numericValue: 2 },
    { type: ActionType.CLICK, selector: 'app-number-of-rooms #next' },
    { type: ActionType.CLICK, selector: 'app-construction-quality div[title="Normal"]' },
    { type: ActionType.CLICK, selector: 'app-construction-quality #Material_0', optional: true, timeout: 500 },
    { type: ActionType.CLICK, selector: 'app-rehabilitated #span_Yes' },
    { type: ActionType.SELECT, selector: 'app-year-rehabilitated #HouseSection__option', stringValue: '2024' },
    { type: ActionType.CLICK, selector: 'app-year-rehabilitated #next' },
    { type: ActionType.CLICK, selector: 'app-protection-system input[name="checkbox_PermanentSecurityStaff"]' },
    { type: ActionType.CLICK, selector: 'app-protection-system #next' },
    { type: ActionType.TYPE, selector: 'app-container #txt_', stringValue: '50000' },
    { type: ActionType.CLICK, selector: 'app-container #next' },
    { type: ActionType.TYPE, selector: 'app-content #txt_', stringValue: '13000' },
    { type: ActionType.CLICK, selector: 'app-content #next' },
    { type: ActionType.CLICK, selector: 'app-cover-type-multi-option #firstQuestion_2 input' },
    { type: ActionType.TYPE, selector: 'app-cover-type-multi-option #txt_ValueOfAllSpecialObjects', stringValue: '20000' },
    { type: ActionType.CLICK, selector: 'app-cover-type-multi-option #next' },
    {
      type: ActionType.TYPE,
      selector: 'app-initial-date-of-insurance #txt_initial_date_insurance',
      executeFunc: async (): Promise<string> => generateStringDate({ addDays: 30 }),
    },
    { type: ActionType.CLICK, selector: 'app-initial-date-of-insurance #next' },
    {
      type: ActionType.TYPE,
      selector: 'app-policy-holder-name-surname #div_Name input',
      executeFunc: async (): Promise<string> => generateRandomName(),
    },
    {
      type: ActionType.TYPE,
      selector: 'app-policy-holder-name-surname #div_FirstSurname input',
      executeFunc: async (): Promise<string> => generateRandomSurname(),
    },
    {
      type: ActionType.TYPE,
      selector: 'app-policy-holder-name-surname #div_SecondSurname input',
      executeFunc: async (): Promise<string> => generateRandomSurname(),
    },
    { type: ActionType.CLICK, selector: 'app-policy-holder-name-surname #next' },
    {
      type: ActionType.TYPE,
      selector: 'app-birthday-policy-holder #txt_dob',
      executeFunc: async (): Promise<string> => generateRandomStringBirthDate({ minAge: 25, maxAge: 60 }),
    },
    { type: ActionType.CLICK, selector: 'app-birthday-policy-holder #next' },
    { type: ActionType.CLICK, selector: 'app-birth-place-policy-holder #radio_724' },
    { type: ActionType.CLICK, selector: 'app-holder-is-defaulter #input_2' },
    { type: ActionType.TYPE, selector: 'app-holder-dni #txt_NIF', executeFunc: (): string => generateRandomDNI() },
    { type: ActionType.CLICK, selector: 'app-holder-dni #next' },
    { type: ActionType.CLICK, selector: 'app-insurance-type #radio_Intermediate' },
    { type: ActionType.TYPE, selector: 'app-email #divEmail input', executeFunc: (): string => generateRandomEmail() },
    { type: ActionType.TYPE, selector: 'app-email #appendPhoneTemplate input', stringValue: '666777888' },
    { type: ActionType.CLICK, selector: 'app-email #divPolitica' },
  ],
  submitAction: { type: ActionType.CLICK, selector: 'app-email #next' },
  isEnabledForLocation: (location: string): boolean => location.includes('-hogar'),
};
